// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/evm/v1/zero_gas_config.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ZeroGasConfig defines the parameters for zero gas fee transactions
type ZeroGasConfig struct {
	// contract_address specifies the target contract address for zero gas fee transactions
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty" yaml:"contract_address"`
	// signatures is a list of function signatures that will have zero gas fee
	// when called on the specified contract_address
	Signatures []string `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" yaml:"signatures"`
}

func (m *ZeroGasConfig) Reset()         { *m = ZeroGasConfig{} }
func (m *ZeroGasConfig) String() string { return proto.CompactTextString(m) }
func (*ZeroGasConfig) ProtoMessage()    {}
func (*ZeroGasConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a68491dbbfc670d8, []int{0}
}
func (m *ZeroGasConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ZeroGasConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ZeroGasConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ZeroGasConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZeroGasConfig.Merge(m, src)
}
func (m *ZeroGasConfig) XXX_Size() int {
	return m.Size()
}
func (m *ZeroGasConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ZeroGasConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ZeroGasConfig proto.InternalMessageInfo

func (m *ZeroGasConfig) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ZeroGasConfig) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type UpdateZeroGasConfigMetadata struct {
	// zero gas configs to be added
	AddZeroGasConfigs []*ZeroGasConfig `protobuf:"bytes,1,rep,name=add_zero_gas_configs,json=addZeroGasConfigs,proto3" json:"add_zero_gas_configs,omitempty"`
	// zero gas configs to be removed
	RemoveZeroGasConfigs []*ZeroGasConfig `protobuf:"bytes,2,rep,name=remove_zero_gas_configs,json=removeZeroGasConfigs,proto3" json:"remove_zero_gas_configs,omitempty"`
}

func (m *UpdateZeroGasConfigMetadata) Reset()         { *m = UpdateZeroGasConfigMetadata{} }
func (m *UpdateZeroGasConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*UpdateZeroGasConfigMetadata) ProtoMessage()    {}
func (*UpdateZeroGasConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a68491dbbfc670d8, []int{1}
}
func (m *UpdateZeroGasConfigMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateZeroGasConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateZeroGasConfigMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateZeroGasConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateZeroGasConfigMetadata.Merge(m, src)
}
func (m *UpdateZeroGasConfigMetadata) XXX_Size() int {
	return m.Size()
}
func (m *UpdateZeroGasConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateZeroGasConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateZeroGasConfigMetadata proto.InternalMessageInfo

func (m *UpdateZeroGasConfigMetadata) GetAddZeroGasConfigs() []*ZeroGasConfig {
	if m != nil {
		return m.AddZeroGasConfigs
	}
	return nil
}

func (m *UpdateZeroGasConfigMetadata) GetRemoveZeroGasConfigs() []*ZeroGasConfig {
	if m != nil {
		return m.RemoveZeroGasConfigs
	}
	return nil
}

func init() {
	proto.RegisterType((*ZeroGasConfig)(nil), "ethermint.evm.v1.ZeroGasConfig")
	proto.RegisterType((*UpdateZeroGasConfigMetadata)(nil), "ethermint.evm.v1.UpdateZeroGasConfigMetadata")
}

func init() {
	proto.RegisterFile("ethermint/evm/v1/zero_gas_config.proto", fileDescriptor_a68491dbbfc670d8)
}

var fileDescriptor_a68491dbbfc670d8 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0x2d, 0xc9, 0x48,
	0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x4f, 0x2d, 0xcb, 0xd5, 0x2f, 0x33, 0xd4, 0xaf, 0x4a, 0x2d,
	0xca, 0x8f, 0x4f, 0x4f, 0x2c, 0x8e, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x80, 0xab, 0xd3, 0x4b, 0x2d, 0xcb, 0xd5, 0x2b, 0x33, 0x94, 0x12, 0x49,
	0xcf, 0x4f, 0xcf, 0x07, 0x4b, 0xea, 0x83, 0x58, 0x10, 0x75, 0x4a, 0x7d, 0x8c, 0x5c, 0xbc, 0x51,
	0xa9, 0x45, 0xf9, 0xee, 0x89, 0xc5, 0xce, 0x60, 0xfd, 0x42, 0x6e, 0x5c, 0x02, 0xc9, 0xf9, 0x79,
	0x25, 0x45, 0x89, 0xc9, 0x25, 0xf1, 0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x4e, 0xd2, 0x9f, 0xee, 0xc9, 0x8b, 0x57, 0x26, 0xe6, 0xe6, 0x58, 0x29, 0xa1,
	0xab, 0x50, 0x0a, 0xe2, 0x87, 0x09, 0x39, 0x42, 0x44, 0x84, 0x4c, 0xb9, 0xb8, 0x8a, 0x33, 0xd3,
	0xf3, 0x12, 0x4b, 0x4a, 0x8b, 0x52, 0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0x38, 0x9d, 0x44, 0x3f,
	0xdd, 0x93, 0x17, 0x84, 0x98, 0x80, 0x90, 0x53, 0x0a, 0x42, 0x52, 0xa8, 0x74, 0x9c, 0x91, 0x4b,
	0x3a, 0xb4, 0x20, 0x25, 0xb1, 0x24, 0x15, 0xc5, 0x59, 0xbe, 0xa9, 0x25, 0x89, 0x29, 0x89, 0x25,
	0x89, 0x42, 0x01, 0x5c, 0x22, 0x89, 0x29, 0x29, 0xf1, 0x68, 0xbe, 0x06, 0x39, 0x91, 0x59, 0x83,
	0xdb, 0x48, 0x5e, 0x0f, 0xdd, 0xdf, 0x7a, 0x28, 0xc6, 0x04, 0x09, 0x26, 0xa6, 0xa4, 0xa0, 0x88,
	0x14, 0x0b, 0x85, 0x71, 0x89, 0x17, 0xa5, 0xe6, 0xe6, 0x97, 0xa5, 0x62, 0x1a, 0xca, 0x44, 0x9c,
	0xa1, 0x22, 0x10, 0xfd, 0xa8, 0xe6, 0x3a, 0x39, 0x9c, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c,
	0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1,
	0x1c, 0x43, 0x94, 0x5a, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0x2e, 0x28, 0x16,
	0xf3, 0x8b, 0xf5, 0x11, 0xb1, 0x5a, 0x01, 0x8e, 0xd7, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36,
	0x70, 0x1c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x05, 0x74, 0x38, 0x77, 0xf5, 0x01, 0x00,
	0x00,
}

func (m *ZeroGasConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ZeroGasConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZeroGasConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Signatures[iNdEx])
			copy(dAtA[i:], m.Signatures[iNdEx])
			i = encodeVarintZeroGasConfig(dAtA, i, uint64(len(m.Signatures[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintZeroGasConfig(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateZeroGasConfigMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateZeroGasConfigMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateZeroGasConfigMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemoveZeroGasConfigs) > 0 {
		for iNdEx := len(m.RemoveZeroGasConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RemoveZeroGasConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZeroGasConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.AddZeroGasConfigs) > 0 {
		for iNdEx := len(m.AddZeroGasConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AddZeroGasConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZeroGasConfig(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintZeroGasConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovZeroGasConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ZeroGasConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovZeroGasConfig(uint64(l))
	}
	if len(m.Signatures) > 0 {
		for _, s := range m.Signatures {
			l = len(s)
			n += 1 + l + sovZeroGasConfig(uint64(l))
		}
	}
	return n
}

func (m *UpdateZeroGasConfigMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AddZeroGasConfigs) > 0 {
		for _, e := range m.AddZeroGasConfigs {
			l = e.Size()
			n += 1 + l + sovZeroGasConfig(uint64(l))
		}
	}
	if len(m.RemoveZeroGasConfigs) > 0 {
		for _, e := range m.RemoveZeroGasConfigs {
			l = e.Size()
			n += 1 + l + sovZeroGasConfig(uint64(l))
		}
	}
	return n
}

func sovZeroGasConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozZeroGasConfig(x uint64) (n int) {
	return sovZeroGasConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ZeroGasConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZeroGasConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ZeroGasConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ZeroGasConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGasConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGasConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZeroGasConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateZeroGasConfigMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZeroGasConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateZeroGasConfigMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateZeroGasConfigMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddZeroGasConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGasConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddZeroGasConfigs = append(m.AddZeroGasConfigs, &ZeroGasConfig{})
			if err := m.AddZeroGasConfigs[len(m.AddZeroGasConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveZeroGasConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGasConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoveZeroGasConfigs = append(m.RemoveZeroGasConfigs, &ZeroGasConfig{})
			if err := m.RemoveZeroGasConfigs[len(m.RemoveZeroGasConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZeroGasConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZeroGasConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipZeroGasConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowZeroGasConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZeroGasConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZeroGasConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthZeroGasConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupZeroGasConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthZeroGasConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthZeroGasConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowZeroGasConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupZeroGasConfig = fmt.Errorf("proto: unexpected end of group")
)
