// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/evm/v1/zero_gas.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ZeroGas defines the parameters for zero gas fee transactions
type ZeroGas struct {
	// contract_address specifies the target contract address for zero gas fee transactions
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty" yaml:"contract_address"`
	// signatures is a list of function signatures that will have zero gas fee
	// when called on the specified contract_address
	Signatures []string `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" yaml:"signatures"`
}

func (m *ZeroGas) Reset()         { *m = ZeroGas{} }
func (m *ZeroGas) String() string { return proto.CompactTextString(m) }
func (*ZeroGas) ProtoMessage()    {}
func (*ZeroGas) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5ca33d3a7a6d940, []int{0}
}
func (m *ZeroGas) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ZeroGas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ZeroGas.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ZeroGas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZeroGas.Merge(m, src)
}
func (m *ZeroGas) XXX_Size() int {
	return m.Size()
}
func (m *ZeroGas) XXX_DiscardUnknown() {
	xxx_messageInfo_ZeroGas.DiscardUnknown(m)
}

var xxx_messageInfo_ZeroGas proto.InternalMessageInfo

func (m *ZeroGas) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ZeroGas) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type UpdateZeroGasMetadata struct {
	// zero gas items to be added
	AddItems []*ZeroGas `protobuf:"bytes,1,rep,name=add_items,json=addItems,proto3" json:"add_items,omitempty"`
	// zero gas items to be removed
	RemoveItems []*ZeroGas `protobuf:"bytes,2,rep,name=remove_items,json=removeItems,proto3" json:"remove_items,omitempty"`
}

func (m *UpdateZeroGasMetadata) Reset()         { *m = UpdateZeroGasMetadata{} }
func (m *UpdateZeroGasMetadata) String() string { return proto.CompactTextString(m) }
func (*UpdateZeroGasMetadata) ProtoMessage()    {}
func (*UpdateZeroGasMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5ca33d3a7a6d940, []int{1}
}
func (m *UpdateZeroGasMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateZeroGasMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateZeroGasMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateZeroGasMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateZeroGasMetadata.Merge(m, src)
}
func (m *UpdateZeroGasMetadata) XXX_Size() int {
	return m.Size()
}
func (m *UpdateZeroGasMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateZeroGasMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateZeroGasMetadata proto.InternalMessageInfo

func (m *UpdateZeroGasMetadata) GetAddItems() []*ZeroGas {
	if m != nil {
		return m.AddItems
	}
	return nil
}

func (m *UpdateZeroGasMetadata) GetRemoveItems() []*ZeroGas {
	if m != nil {
		return m.RemoveItems
	}
	return nil
}

func init() {
	proto.RegisterType((*ZeroGas)(nil), "ethermint.evm.v1.ZeroGas")
	proto.RegisterType((*UpdateZeroGasMetadata)(nil), "ethermint.evm.v1.UpdateZeroGasMetadata")
}

func init() { proto.RegisterFile("ethermint/evm/v1/zero_gas.proto", fileDescriptor_a5ca33d3a7a6d940) }

var fileDescriptor_a5ca33d3a7a6d940 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x2d, 0xc9, 0x48,
	0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x4f, 0x2d, 0xcb, 0xd5, 0x2f, 0x33, 0xd4, 0xaf, 0x4a, 0x2d,
	0xca, 0x8f, 0x4f, 0x4f, 0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0x2b, 0xd0,
	0x4b, 0x2d, 0xcb, 0xd5, 0x2b, 0x33, 0x94, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x4b, 0xea, 0x83,
	0x58, 0x10, 0x75, 0x4a, 0x1d, 0x8c, 0x5c, 0xec, 0x51, 0xa9, 0x45, 0xf9, 0xee, 0x89, 0xc5, 0x42,
	0x6e, 0x5c, 0x02, 0xc9, 0xf9, 0x79, 0x25, 0x45, 0x89, 0xc9, 0x25, 0xf1, 0x89, 0x29, 0x29, 0x45,
	0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x4e, 0xd2, 0x9f, 0xee, 0xc9, 0x8b, 0x57,
	0x26, 0xe6, 0xe6, 0x58, 0x29, 0xa1, 0xab, 0x50, 0x0a, 0xe2, 0x87, 0x09, 0x39, 0x42, 0x44, 0x84,
	0x4c, 0xb9, 0xb8, 0x8a, 0x33, 0xd3, 0xf3, 0x12, 0x4b, 0x4a, 0x8b, 0x52, 0x8b, 0x25, 0x98, 0x14,
	0x98, 0x35, 0x38, 0x9d, 0x44, 0x3f, 0xdd, 0x93, 0x17, 0x84, 0x98, 0x80, 0x90, 0x53, 0x0a, 0x42,
	0x52, 0xa8, 0xd4, 0xcb, 0xc8, 0x25, 0x1a, 0x5a, 0x90, 0x92, 0x58, 0x92, 0x0a, 0x75, 0x90, 0x6f,
	0x6a, 0x49, 0x62, 0x4a, 0x62, 0x49, 0xa2, 0x90, 0x19, 0x17, 0x67, 0x62, 0x4a, 0x4a, 0x7c, 0x66,
	0x49, 0x6a, 0x2e, 0xc8, 0x45, 0xcc, 0x1a, 0xdc, 0x46, 0x92, 0x7a, 0xe8, 0x1e, 0xd4, 0x83, 0xea,
	0x0a, 0xe2, 0x48, 0x4c, 0x49, 0xf1, 0x04, 0x29, 0x15, 0xb2, 0xe1, 0xe2, 0x29, 0x4a, 0xcd, 0xcd,
	0x2f, 0x4b, 0x85, 0x6a, 0x65, 0x22, 0xa4, 0x95, 0x1b, 0xa2, 0x1c, 0xac, 0xdb, 0xc9, 0xe1, 0xc4,
	0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1,
	0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0xd4, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93,
	0xf4, 0x92, 0xf3, 0x73, 0x41, 0xc1, 0x9f, 0x5f, 0xac, 0x8f, 0x88, 0x8e, 0x0a, 0x70, 0x84, 0x94,
	0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0xc3, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x00, 0xf2, 0x20, 0xae, 0x01, 0x00, 0x00,
}

func (m *ZeroGas) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ZeroGas) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ZeroGas) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Signatures[iNdEx])
			copy(dAtA[i:], m.Signatures[iNdEx])
			i = encodeVarintZeroGas(dAtA, i, uint64(len(m.Signatures[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintZeroGas(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateZeroGasMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateZeroGasMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateZeroGasMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemoveItems) > 0 {
		for iNdEx := len(m.RemoveItems) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RemoveItems[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZeroGas(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.AddItems) > 0 {
		for iNdEx := len(m.AddItems) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AddItems[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintZeroGas(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintZeroGas(dAtA []byte, offset int, v uint64) int {
	offset -= sovZeroGas(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ZeroGas) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovZeroGas(uint64(l))
	}
	if len(m.Signatures) > 0 {
		for _, s := range m.Signatures {
			l = len(s)
			n += 1 + l + sovZeroGas(uint64(l))
		}
	}
	return n
}

func (m *UpdateZeroGasMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AddItems) > 0 {
		for _, e := range m.AddItems {
			l = e.Size()
			n += 1 + l + sovZeroGas(uint64(l))
		}
	}
	if len(m.RemoveItems) > 0 {
		for _, e := range m.RemoveItems {
			l = e.Size()
			n += 1 + l + sovZeroGas(uint64(l))
		}
	}
	return n
}

func sovZeroGas(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozZeroGas(x uint64) (n int) {
	return sovZeroGas(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ZeroGas) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZeroGas
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ZeroGas: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ZeroGas: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGas
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZeroGas
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGas
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGas
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZeroGas
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGas
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZeroGas(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZeroGas
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateZeroGasMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZeroGas
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateZeroGasMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateZeroGasMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddItems", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGas
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZeroGas
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGas
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddItems = append(m.AddItems, &ZeroGas{})
			if err := m.AddItems[len(m.AddItems)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveItems", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZeroGas
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZeroGas
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZeroGas
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoveItems = append(m.RemoveItems, &ZeroGas{})
			if err := m.RemoveItems[len(m.RemoveItems)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZeroGas(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZeroGas
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipZeroGas(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowZeroGas
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZeroGas
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZeroGas
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthZeroGas
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupZeroGas
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthZeroGas
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthZeroGas        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowZeroGas          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupZeroGas = fmt.Errorf("proto: unexpected end of group")
)
